# Gitpod Configuration for Streaming Platform Demo

image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
    name: Frontend
    description: Frontend Visualization App
  - port: 8000
    onOpen: ignore
    name: Backend API
    description: Backend API Service
  - port: 3306
    onOpen: ignore
    name: Database
    description: SQLite Database Service

tasks:
  - name: Setup Environment
    init: |
      echo "Setting up development environment..."
      mkdir -p logs
    command: |
      echo "Environment ready!"
      echo "Starting services in separate terminals..."
  
  - name: Database
    init: |
      cd services/database
      npm install
    command: |
      cd services/database
      npm run start

  - name: Backend Services
    init: |
      cd services/backend
      npm install
    command: |
      cd services/backend
      npm run dev

  - name: Frontend
    init: |
      cd frontend
      npm install
    command: |
      cd frontend
      npm run dev

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker
    - mtxr.sqltools
    - mtxr.sqltools-driver-pg
    - mikestead.dotenv
    - graphql.vscode-graphql


