mcpServers:
  atlassian-mcp:
    command: npx
    args:
      - "@modelcontextprotocol/server-fetch"
      - "https://mcp.atlassian.com/v1/sse"
    env: {}

tools:
  - jira-integration
  - compass-integration
  - confluence-integration

server_endpoint: https://mcp.atlassian.com/v1/sse
authentication: oauth2.1
description: Official Atlassian MCP server supporting Jira, Compass, and Confluence
